language: go

go:
- "1.15" 			
env:
- GO111MODULE=on

before_install:
# Instalamos homebew para luego poder instalar Task
- curl -sL https://taskfile.dev/install.sh | sh

install:
#Instalamos Task
- brew install go-task/tap/go-task

script:
- task syntax_check
