# appveyor.yml
image: Ubuntu

# Solo queremos testear
build: off

# Probamos diferentes versiones de Go (menos la última que es es Travis)
stack: 
  - go 1.14
  - go 1.13

# Instalamos el gestor de tareas Task
install:
  - ./install-task.sh

# Ejecutamos los tests mediante Task
test_script:
  - task test
