version: '3'

tasks:
  syntax_check:
    desc: comprobar sintaxis
    summary: |
      Correción de sintaxis

      Sirve para comprobar que la sintaxis de los archivos es correcta
    cmds:
      - gofmt -e .  > /dev/null

  format_code:
    desc: formatear código
    summary: |
      Formateo de código

      Al ejecutarla, modifica el código para que sea más fácil de leer dando el formato adecuado
    cmds:
      - gofmt -w . 

  test:
    desc: ejecutar tests
    summary: |
      Tests

      Automatización de la ejecución de los tests
    cmds:
      - go test ./tests/ -v

  docker_local:
    desc: ejecutar docker en local
    summary: |
      Ejecución de docker

      Mediante esta orden ejecutamos directamente el contenedor de docker creado para la ejecución
      de los test. Monta directamente el directorio actual en /app/test y se elimina tras la ejecución
      con la orden --rm
    cmds: 
      - docker run --rm -t -v `pwd`:/app/test pedromfc/evaluaugr

  build:
    desc: generar ejecutables
    summary: |
      Generar ejecutables

      Mediante esta orden creamos los ejecutables de la aplicación. Como se puede llevar a cabo directamente
      con la orden install, no hacemos realmente nada
    cmds: 
      - echo "Todo OK. Construimos en install"
  
  install:
    desc: instalar el programa
    summary: |
      Instalar el programa

      Mediante esta orden instalamos el programa. Construye los ejecutables y los mueve directamente al
      directrio $GOPATH/bin
    cmds: 
      - go install ./...