// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import modelspre "github.com/PedroMFC/EvaluaUGR/internal/micropre/modelspre"

// IPreSaver is an autogenerated mock type for the IPreSaver type
type IPreSaver struct {
	mock.Mock
}

// AsignaturaRegistrada provides a mock function with given fields: asignatura
func (_m *IPreSaver) AsignaturaRegistrada(asignatura string) bool {
	ret := _m.Called(asignatura)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(asignatura)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CrearAsignatura provides a mock function with given fields: asignatura
func (_m *IPreSaver) CrearAsignatura(asignatura string) {
	_m.Called(asignatura)
}

// GuardarPregunta provides a mock function with given fields: asignatura, pre
func (_m *IPreSaver) GuardarPregunta(asignatura string, pre *modelspre.Pregunta) {
	_m.Called(asignatura, pre)
}

// ObtenerPregunta provides a mock function with given fields: asignatura
func (_m *IPreSaver) ObtenerPregunta(asignatura string) []modelspre.Pregunta {
	ret := _m.Called(asignatura)

	var r0 []modelspre.Pregunta
	if rf, ok := ret.Get(0).(func(string) []modelspre.Pregunta); ok {
		r0 = rf(asignatura)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]modelspre.Pregunta)
		}
	}

	return r0
}

// Responder provides a mock function with given fields: asignatura, id, res
func (_m *IPreSaver) Responder(asignatura string, id int, res *modelspre.Respuesta) error {
	ret := _m.Called(asignatura, id, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, *modelspre.Respuesta) error); ok {
		r0 = rf(asignatura, id, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
