# GitHub Action para automatizar la subida del contenedor a GitHub Container Registry
# El enlace de referencia es el siguiente
# https://github.com/marketplace/actions/docker-build-tag-push

name: Subir imagen a GitHub Container Registry

on: 
  push:
    paths:
      - 'Dockerfile'

jobs:
  Automatic-gcr:
    name: Pull a GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: evaluaugr/task-go-alpine
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }} 

      # Por si se quiere automatizar la subida a DcokerHub también
      #- uses: mr-smithers-excellent/docker-build-push@v3
      #  with:
      #    image: pedromfc/evaluaugr
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}